name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: CIE.AspNetCore.Authentication
    - name: Build
      run: dotnet build --no-restore
      working-directory: CIE.AspNetCore.Authentication
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: CIE.AspNetCore.Authentication
    - name: Restore dependencies WebApp
      run: dotnet restore
      working-directory: CIE.AspNetCore.Authentication/CIE.AspNetCore.WebApp
    - name: Build WebApp
      run: dotnet build --no-restore
      working-directory: CIE.AspNetCore.Authentication/CIE.AspNetCore.WebApp
    - name: Update apt repo
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl xmlsec1 python3-pip
    - name: Install spid-compliant-certificates cryptography correct version
      run: sudo pip install -Iv cryptography==35.0.0
    - name: Install spid-sp-test
      run: sudo pip install spid-sp-test --upgrade --no-cache
    - name: Run CIE.AspNetCore.WebApp
      working-directory: CIE.AspNetCore.Authentication/CIE.AspNetCore.WebApp
      run: dotnet bin/Debug/net6.0/CIE.AspNetCore.WebApp.dll &
    - name: Test Metadata spid-sp-public with spid-sp-test
      run: spid_sp_test --metadata-url https://localhost:5001/metadata-cie/metadata1.xml --extra --debug ERROR --profile cie-sp-public
    - name: Test Metadata spid-sp-private with spid-sp-test
      run: spid_sp_test --metadata-url https://localhost:5001/metadata-cie/metadata3.xml --extra --debug ERROR --profile cie-sp-private 
